-- MySQL Script generated by MySQL Workbench
-- mer. 21 févr. 2018 13:13:50 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fuji
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fuji
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fuji` DEFAULT CHARACTER SET utf8 ;
USE `fuji` ;

-- -----------------------------------------------------
-- Table `fuji`.`Zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fuji`.`Zone` ;

CREATE TABLE IF NOT EXISTS `fuji`.`Zone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idZones_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fuji`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fuji`.`User` ;

CREATE TABLE IF NOT EXISTS `fuji`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password_digest` VARCHAR(45) NOT NULL,
  `money` INT NULL DEFAULT 0,
  `zone_id` INT NOT NULL,
  PRIMARY KEY (`id`, `zone_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `idUser_UNIQUE` (`id` ASC),
  INDEX `fk_User_Zones1_idx` (`zone_id` ASC),
  CONSTRAINT `fk_User_Zones1`
    FOREIGN KEY (`zone_id`)
    REFERENCES `fuji`.`Zone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fuji`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fuji`.`Order` ;

CREATE TABLE IF NOT EXISTS `fuji`.`Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATE NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `idOrders_UNIQUE` (`id` ASC),
  INDEX `fk_Orders_User1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Orders_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `fuji`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fuji`.`Discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fuji`.`Discount` ;

CREATE TABLE IF NOT EXISTS `fuji`.`Discount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pourcentage` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idDiscount_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fuji`.`Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fuji`.`Categorie` ;

CREATE TABLE IF NOT EXISTS `fuji`.`Categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `discount-id` INT NOT NULL,
  PRIMARY KEY (`id`, `discount-id`),
  UNIQUE INDEX `idCategories_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC),
  INDEX `fk_Categories_Discount_idx` (`discount-id` ASC),
  CONSTRAINT `fk_Categories_Discount`
    FOREIGN KEY (`discount-id`)
    REFERENCES `fuji`.`Discount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fuji`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fuji`.`Product` ;

CREATE TABLE IF NOT EXISTS `fuji`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prix` INT NOT NULL,
  `categorie_id` INT NOT NULL,
  PRIMARY KEY (`id`, `categorie_id`),
  UNIQUE INDEX `idProducts_UNIQUE` (`id` ASC),
  INDEX `fk_Products_Categories1_idx` (`categorie_id` ASC),
  CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `fuji`.`Categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fuji`.`Order_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fuji`.`Order_products` ;

CREATE TABLE IF NOT EXISTS `fuji`.`Order_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `order_id`, `product_id`),
  UNIQUE INDEX `idOrder_products_UNIQUE` (`id` ASC),
  INDEX `fk_Order_products_Orders1_idx` (`order_id` ASC),
  INDEX `fk_Order_products_Products1_idx` (`product_id` ASC),
  CONSTRAINT `fk_Order_products_Orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `fuji`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_products_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `fuji`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
